// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3QSBoXrkY2L8MQOSF0Z6W-apcwXIMFa4',
    appId: '1:134712045826:web:2567447bd9623ce058521b',
    messagingSenderId: '134712045826',
    projectId: 'sharp-reps',
    authDomain: 'sharp-reps.firebaseapp.com',
    storageBucket: 'sharp-reps.appspot.com',
    measurementId: 'G-ZL075KZ41X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbvzv5kKj6pcS87-UjWnQVGyUvBjhhJD8',
    appId: '1:134712045826:android:0885917e22efe99d58521b',
    messagingSenderId: '134712045826',
    projectId: 'sharp-reps',
    storageBucket: 'sharp-reps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ht3H_F6BEoMxFInnhKyNneAYNICkA_w',
    appId: '1:134712045826:ios:f5acadccf9e8587958521b',
    messagingSenderId: '134712045826',
    projectId: 'sharp-reps',
    storageBucket: 'sharp-reps.appspot.com',
    iosClientId: '134712045826-fvha9g564ff75o2hqund9p3iepek6oon.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharpReps',
  );
}
